version: '3.7'

services: 
    app:
        build: 
            context: .
        volumes: 
            - ./src:/src
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        ports: 
            - 8000:8000
        depends_on: 
            - db
    db:
        environment: 
            # - "POSTGRES_HOST_AUTH_METHOD=trust"
            POSTGRES_PASSWORD: password
        image: postgis/postgis:13-master
